//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab13var1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int IdMatch { get; set; }
        public int HomeTeam { get; set; }
        public int GuestTeam { get; set; }
        public string Score { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Teams Teams { get; set; }
        public virtual Teams Teams1 { get; set; }
    }
}
