//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab13var1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int IdPlayer { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public System.DateTime Birthday { get; set; }
        public byte[] Photo { get; set; }
        public int PhoneNumber { get; set; }
        public int IdTeam { get; set; }
    
        public virtual Teams Teams { get; set; }
    }
}
